kind: pipeline
name: almin

workspace:
  base: /app
  path: src/almin

steps:
- name: deploy
  image: emirjrs/node:v1
  commands:
  - pwd
  - node -v
  - ls -l
  - cd ./examples/todomvc/ && ls -l
  - npm install
  - npm test
#  - npm start
publish:
  image: plugins/docker
  repo: emirjrs/node
  tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
  secrets: [ docker_username, docker_password ]
  when:
    event: [ push ]
    branch: master
