---
kind: pipeline
name: almin

workspace:
  base: /app
  path: src/almin

steps:
- name: build
  image: node
  commands:
  - node -v
  - cd examples/todomvc
  - npm install

- name: test
  image: node
  commands:
  - cd examples/todomvc
  - npm test

- name: deploy
  image: emirjrs/node:v1
  - cd examples/todomvc
  - npm start &
  - sleep 5
  - curl localhost:8080
  - sleep 5
