kind: pipeline
name: almin

workspace:
  base: /app
  path: src/almin

steps:
- name: deploy
  image: emirjrs/node:v1
  commands:
  - pwd
  - node -v
  - cd ./examples/todomevc/ && ls -l
  - cd ./examples/todomevc/ && npm install
  - cd ./examples/todomevc/ && npm test
  - cd ./examples/todomevc/ && npm start
