kind: pipeline
name: almin

workspace:
  base: /app
  path: src/almin

steps:
- name: deploy
  image: emirjrs/node:v1
  commands:
  - pwd
  - node -v
  - ls -l
  - cd ./examples/todomvc/ && ls -l
  - npm install
  - npm test
  - npm start
