kind: pipeline
name: almin

workspace:
  path: ./almin/examples/todomvc/

steps:
- name: deploy
  image: emirjrs/node:v1
  commands:
  - pwd
  - cd examples/todomvc & npm install
  - cd examples/todomvc & npm start
