kind: pipeline
name: almin

workspace:
  base: /app
  path: almin/examples/todomvc/

steps:
- name: deploy
  image: emirjrs/node:v1
  commands:
  - pwd
  - ls -l
  - node -v
  - npm install
  - npm test
  - npm start
