ui: mocha-bdd
scripts:
  - https://cdn.polyfill.io/v2/polyfill.min.js
  - https://unpkg.com/console-polyfill
browsers:
  - name: internet explorer
    version: 11..latest
  - name: microsoftedge
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: [-1..latest]
  - name: firefox
    version: [-1..latest]
