ui: mocha-bdd
scripts:
  - https://cdn.polyfill.io/v2/polyfill.min.js
browsers:
  - name: internet explorer
    version: 9..latest
  - name: microsoftedge
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: [latest]
  - name: firefox
    version: [latest]
