// LICENSE : MIT
"use strict";
/**
 * DispatcherPayloadMeta is a meta object for dispatcher.
 * If `isTrusted` is true, the object is created by System(= Almin).
 * The user can get this meta object together with dispatched `payload` object
 * @example
 * context.onDispatch((payload, meta) => {});
 */
export default class DispatcherPayloadMeta {
    /**
     * @param {UseCase} [useCase]
     * @param {UseCase|Dispatcher} [parentDispatcher]
     * @param {boolean} isTrusted true if the payload object is generated by Almin.
     */
    constructor({
        useCase,
        parentDispatcher,
        isTrusted
    } = {}) {
        /**
         * @param {UseCase|Dispatcher|null|undefined} useCase A reference to the useCase/dispatcher to which the payload was originally dispatched.
         * @readonly
         * @public
         */
        this.useCase = useCase;
        /**
         * Parent dispatcher/useCase of the `this.useCase`,
         * @param {UseCase|Dispatcher|null|undefined}
         * @readonly
         * @public
         */
        this.parentDispatcher = parentDispatcher;
        /**
         *  timeStamp is created time of the meta.
         * @type {number}
         * @readonly
         * @public
         */
        this.timeStamp = Date.now();
        /**
         * If the payload object is generated by Almin, true
         * The use can use it for detecting "Is the payload generated by system(almin)?".
         * It is similar with https://www.w3.org/TR/DOM-Level-3-Events/#trusted-events
         * @type {boolean}
         * @readonly
         * @public
         */
        this.isTrusted = isTrusted;
    }
}